project:
  type: website
  output-dir: _site

website:
  title: "Jornada Data Commons: Ed Pages"
  description: "Environmental data science education for the Jornada Basin LTER and USDA-ARS Jornada Experimental Range. Contact: jornada.data@nmsu.edu."
  favicon: img/jrn-logo-light.png
  site-url: https://jornada-im.github.io/jeds/
  repo-url: https://github.com/jornada-im/jeds
  issue-url: https://github.com/jornada-im/jeds/issues/new/choose
  repo-branch: main
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  #announcement: 
  #  content: "**Prerelease version**: This content is under development. See [here](https://ediorg.github.io/data-package-best-practices/) for community-accepted documents." 
   # position: above-navbar
   # dismissable: false
   # type: danger
  search:
    location: navbar
  navbar:
    logo: img/jrn-logo-light.png
    background: primary
    left:
      - text: "Lessons"
        href: docs/lessons/index.qmd
      - text: "Presentations"
        href: docs/slides/index.qmd
      - text: "Workshops"
        href: workshops/index.qmd
      - text: "Commons Home"
        href: https://jornada-im.github.io
    tools:
      - icon: github
        href: https://github.com/jornada-im/jeds
        text: The Jornada Ed Pages GitHub repository

  sidebar:
    - title: "Lessons"
      id: lessons_sb
      style: floating
      collapse-level: 2
      contents: "docs/lessons/*.qmd"
        # - href: docs/lessons/index.qmd
        #   text: "Introduction"
        # - href: docs/researcher/starting-research.qmd
        #   text: "Starting research"
    - title: "Presentations"
      id: slides_sb
      style: floating
      collapse-level: 2
      contents: "docs/slides/*.qmd"

execute:
  freeze: auto

bibliography: references.bib

format:
  html:
    theme: sandstone
    highlight-style: pygments
    #code-block-bg: true
    #code-block-border-left: "#31BAE9"
    fontsize: 1.0em
    toc: true

