---
title: Welcome to the Jornada Environmental Data Science pages (JEDS)
format:
  html:
    css: styles.css
from: markdown+emoji
---

These pages contain media and hands-on lessons for environmental data science education at the [Jornada Basin LTER (JRN)]({{< var url.jrn_website >}}) and [Jornada Experimental Range (JER)]({{< var url.jer_website >}}) programs. Our aim is to teach environmental data science concepts and skills to Jornada researchers using accessible methods and relatable data.

::: {.callout-caution collapse="false" appearance="default"}
## WARNING! This site is under construction
We're in the process of rebuilding this site with Quarto. A few things don't work yet. Report problems and suggest additions in the [issue tracker](https://github.com/jornada-im/jeds/issues).

If you see a construction symbol (:construction:) we're still working on that part!

:::

## Setting up your environment

Most tutorials have been developed for learners using `R`, `python`, and other open-source tools. To set up an environment to work through lessons on your own or in a workshop, follow the [setup instructions](./html/setup.html) that apply to your lesson. Lessons rely on either simulated data or Jornada data hosted at EDI. The [teaching datasets page](./html/teaching-datasets.html) will introduce these datasets and how to load them. Additional required software packages and suggestions for loading the data are given at the start of each lesson.

## Lessons

1. [Hypothesis testing with general linear models and mixed models](./html/statistical-inference-linear-and-mixed.html)
2. [Using git and GitHub as a researcher](./html/git-and-github-for-research.html)
3. [Extras: Data visualization with ggplot](./html/data-viz-with-ggplot.html)

## Upcoming workshops

* [Spring 2023 Data Therapy geospatial data tutorials](./workshops/2023-data-therapy-geospatial/index)
* The 2023 Jornada Desert Ecology Short Course will include a [Data Carpentries R workshop](https://datacarpentry.org/R-ecology-lesson/).

## Past workshops

* [Fall 2022 Data Therapy Git/GitHub tutorials](./workshops/2022-data-therapy-git-github/index) 
* [2022-06-29 - Jornada Desert Ecology Short Course](./workshops/20220629-jrn-ecology-short-course/index)
